version: '3.7'

services:
  chat-db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=chat-db
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

  chat-service:
    build: ./chat-service
    ports:
      - '8086:8086'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chat-db:5432/chat-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_APPLICATION_NAME: chat-service
    depends_on:
      - chat-db

  user-db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
    ports:
      - '5433:5432' # Use a different host port to avoid conflict

  user-service:
    build: ./user-service
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_APPLICATION_NAME: user-service
    depends_on:
      - user-db

  post-db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=post-db
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
    ports:
      - '5434:5432' # Use a different host port to avoid conflict

  post-service:
    build: ./post-service
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://post-db:5432/post-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_APPLICATION_NAME: post-service
    depends_on:
      - post-db



