spring:
  security:
    user:
      name: amine
      password: amine
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://postgres:5432/post-db
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8082
